config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {:registrations => 'customers/registrations', :sessions => 'customers/sessions'}
  devise_for :admins, controllers: {:sessions => 'admins/sessions'}

  # redirect_toにてsign_outを使用するために必要
  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end

  # Aboutページ用
  get 'items/about'

  # Customerトップでのジャンル指定用
  get 'items/genre/:id' => 'items#index', as: 'items_genre'

  resources :items
  resources :orders
  # CUstomer退会確認画面用
  get 'customers/exit'
  resources :customers

  resources :addresses
  resources :order_items

  get 'cart_items/info'
  post 'cart_items/confirm'
  get 'cart_items/confirm'
  get 'cart_items/thanks'
  resources :cart_items do
    collection do
      delete :empty
    end
  end

  root 'items#index'


  namespace :admins do
    resources :customers
  end

  namespace :admins do
    resources :orders
  end

  namespace :admins do
    resources :genres
  end

  namespace :admins do
    resources :items

  end
  get 'admins/top'

  namespace :device do
    get 'registrations/new'
    get 'registrations/create'
    get 'registrations/destroy'
  end

  namespace :admins do
    get 'sessions/new'
    get 'sessions/create'
    get 'sessions/destroy'
  end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :orders, dependent: :destroy
         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy

         validates :email, presence: true
         validates :name_first, presence: true
         validates :name_last, presence: true
         validates :name_first_kana, presence: true
         validates :name_last_kana, presence: true
         validates :postal_code, presence: true
         validates :address, presence: true
         validates :phone_number, presence: true
         # validates :is_active, presence: true
         # ブーリアン型で判別するときはpresencd:trueが必要ない(yu)


def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
end

# 退会済み会員のログインを受け付けない(aki)
def active_for_authentication?
  super && is_active
end

# admin側customer検索機能
  def self.search(search)
    if search
      # 苗字or名前or各かなor(苗字+名前)で検索
      Customer.where("name_last IN (?) OR name_first IN (?) OR name_last_kana IN (?) OR name_first_kana IN (?) OR (name_last || name_first) IN (?) OR (name_last_kana || name_first_kana) IN (?)" , search, search, search, search, search, search)
    else
      Customer.all
    end
  end

end

app/controllers/admins/customers_controller.rb
class Admins::CustomersController < ApplicationController
  before_action :authenticate_admin!

  # kaminari表示数設定
  PER = 10

  def index
    # 検索パラメータの有無による分岐
    if params[:search] != nil
      customers = Customer.search(params[:search])
      flash.now[:notice] = "検索の結果 #{customers.count} 件みつかりました"
    else
      # 検索パラメータがない場合（通常）は全ての顧客を渡す
      customers = Customer.all
      flash.now[:notice] = "全 #{customers.count} 件あります"
    end

    # kaminari用
    @customers = customers.page(params[:page]).per(PER)
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def personal
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:success] = "顧客情報を更新しました"
      redirect_to admins_customer_path(@customer)
    else
      flash.now[:danger] = "顧客情報の更新に失敗しました"
      render action: :edit
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :name_first, :name_last, :name_first_kana, :name_last_kana, :email, :postal_code, :address, :phone_number, :is_active)
  end
end

app/controllers/customers/confirmations_controller.rb
# frozen_string_literal: true

class Customers::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/customers/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Customers::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/customers/passwords_controller.rb
# frozen_string_literal: true

class Customers::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/customers/registrations_controller.rb
# frozen_string_literal: true

class Customers::RegistrationsController < Devise::RegistrationsController

    def after_sign_up_path_for(resource)
    items_path
    end

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

end

app/controllers/customers/sessions_controller.rb
# frozen_string_literal: true

class Customers::SessionsController < Devise::SessionsController
  # adminとの2重signinを防止
   before_action :is_admin_check

   # adminでログインしている場合adminのTOPへリダイレクト
   def is_admin_check
    if current_admin
      flash[:danger] = "管理者ユーザからサインアウトしてください"
      redirect_to admins_top_path
    end
   end

  def after_sign_in_path_for(resource)
    root_path
  end

  def after_sign_out_path_for(resource)
    items_path
  end
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

end

app/controllers/customers/unlocks_controller.rb
# frozen_string_literal: true

class Customers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :authenticate_customer!

  def show
  	@customer = Customer.find(params[:id])
  end

  def edit
  	@customer = Customer.find(params[:id])
  end

  def update
  	@customer = Customer.find(params[:id])

    # exitより（退会画面）来た場合の退会処理
    source = Rails.application.routes.recognize_path(request.referrer)
    if source[:action] == "exit"
      @customer.update(is_active: false)
      flash[:success] = "退会処理が完了しました"
      redirect_to destroy_customer_session_path
    else
      if @customer.update(customer_params)
        flash[:success] = "顧客情報を更新しました"
        redirect_to customer_path(@customer)
      else
        flash.now[:danger] = "顧客情報を更新できませんでした"
        render :edit
      end
    end
  end

  def exit

    @customer = Customer.find(current_customer.id)
  end

  private
  def customer_params
    params.require(:customer).permit(:name_last, :name_first, :name_last_kana, :name_first_kana, :postal_code, :address, :phone_number, :email)
  end

end

app/helpers/admins/customers_helper.rb
module Admins::CustomersHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/edit.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h3 class="">プロフィール編集</h3>
            <div style="margin: 10px 0 10px 10px; text-align: right;">
                <%= link_to "退会する", customers_exit_path, class: "btn-sm btn-danger"%>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <%= form_for(@customer) do |f| %>
            <div class="panel panel-primary">
                <div class="panel-heading" style="text-align: center;">
                    <b>プロフィール編集フォーム</b>
                </div>
                <table class="table table-bordered table-content">
                    <tbody>
                        <tr>
                            <th class="info">
                                <%= f.label :氏名 %>
                            </th>
                            <td>
                                <%= f.text_field :name_last, class: "text-field-small" %>
                                <%= f.text_field :name_first, class: "text-field-small" %>
                            </td>
                        </tr>
                        <tr>
                            <th class="info">
                                <%= f.label :カナ %>
                            </th>
                            <td>
                                <%= f.text_field :name_last_kana, class: "text-field-small" %>
                                <%= f.text_field :name_first_kana, class: "text-field-small" %>
                            </td>
                        </tr>
                        <tr>
                            <th class="info">
                                <%= f.label :郵便番号 %>(ハイフンなし7桁)
                            </th>
                            <td>
                                <%= f.text_field :postal_code, class: "text-field-lage" %>
                            </td>
                        </tr>
                        <tr>
                            <th class="info">
                                <%= f.label :住所 %>
                            </th>
                            <td>
                                <%= f.text_field :address, class: "text-field-lage" %>
                            </td>
                        </tr>
                        <tr>
                            <th class="info">
                                <%= f.label :電話番号 %>
                            </th>
                            <td>
                                <%= f.text_field :phone_number, class: "text-field-lage" %>
                            </td>
                        </tr>
                        <tr>
                            <th class="info">
                                <%= f.label :メールアドレス %>
                            </th>
                            <td>
                                <%= f.email_field :email, class: "text-field-lage" %>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div style="text-align: center">
            <%= f.submit "編集内容を保存する", class: "btn-sm btn-primary" %>
        </div>
            <% end %>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>

app/views/customers/exit.html.erb
	<div class="row" style="padding-top: 100px;">
		<div class="col-md-2"></div>
		<div class="bg-mask-w">
			<div class="col-md-8"style="text-align: center;">
			    <h3>本当に退会しますか？</h3>
				<p>退会すると、会員登録情報やこれまでの購入履歴が閲覧できなくなります。</p>
				<p>退会する場合は、「退会する」をクリックしてください。</p>
		    </div>
		</div>
	</div>
	<div class="row" style="padding-top: 50px;">
	    <div class="col-md-2"></div>
	    <div class="col-md-4" style="text-align: center;">
	        <%= link_to "退会しない", customer_path(current_customer), class: "btn-sm btn-primary" %>
	    </div>
	    <div class="col-md-4" style="text-align: center;">
	        <%= form_for @customer do |f| %>
				<%= f.submit "退会する", class: "btn-sm btn-danger" %>
	        <% end %>
	    </div>
	    <div class="col-md-2"></div>
	</div>
</div>

app/views/customers/show.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <h3>マイページ</h3>
            <% if @customer.id == current_customer.id %>
            <ul class="list-inline" style="text-align: right;">
                <li class="">
                    <%= link_to "プロフィール編集", edit_customer_path(@customer), class: 'btn-sm btn-primary' %>
                </li>
                <li class="">
                    <%= link_to "パスワード変更", edit_registration_path(@customer), class: 'btn-sm btn-primary' %>
                </li>
            </ul>
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <div class="panel panel-primary">
                <div class="panel-heading" style="text-align: center;">
                    <b>登録情報</b>
                </div>
                <table class="table table-bordered table-content">
                    <tbody>
                        <tr>
                            <th class="info">名前</th>
                            <td>
                                <%= "#{current_customer.name_last}　#{current_customer.name_first}" %>
                            </td>
                        </tr>
                        <tr>
                            <th class="info">カナ</th>
                            <td>
                                <%= "#{current_customer.name_last_kana}　#{current_customer.name_first_kana}" %>
                            </td>
                        </tr>
                        <tr>
                            <th class="info">郵便番号</th>
                            <td>
                                <%= "#{current_customer.postal_code}" %>
                            </td>
                        </tr>
                        <tr>
                            <th class="info">住所</th>
                            <td>
                                <%= "#{current_customer.address}" %>
                            </td>
                        </tr>
                        <tr>
                            <th class="info">電話番号</th>
                            <td>
                                <%= "#{current_customer.phone_number}" %>
                            </td>
                        </tr>
                        <tr>
                            <th class="info">メールアドレス</th>
                            <td>
                                <%= "#{current_customer.email}" %>
                            </td>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-2"></div>
    </div>
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-4" style="margin-top: 10px;">
            <%= link_to addresses_path(@customer), class: 'btn-sm btn-block btn-primary text-align-center' do %>
            配送先一覧
            <% end %>
        </div>
        <div class="col-md-4" style="margin-top: 10px;">
            <%= link_to orders_path(@customer), class: 'btn-sm btn-block btn-primary btn-block text-align-center' do%>注文履歴一覧
            <% end %>
        </div>
        <div class="col-md-2"></div>
    </div>
</div>