config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {:registrations => 'customers/registrations', :sessions => 'customers/sessions'}
  devise_for :admins, controllers: {:sessions => 'admins/sessions'}

  # redirect_toにてsign_outを使用するために必要
  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end

  # Aboutページ用
  get 'items/about'

  # Customerトップでのジャンル指定用
  get 'items/genre/:id' => 'items#index', as: 'items_genre'

  resources :items
  resources :orders
  # CUstomer退会確認画面用
  get 'customers/exit'
  resources :customers

  resources :addresses
  resources :order_items

  get 'cart_items/info'
  post 'cart_items/confirm'
  get 'cart_items/confirm'
  get 'cart_items/thanks'
  resources :cart_items do
    collection do
      delete :empty
    end
  end

  root 'items#index'


  namespace :admins do
    resources :customers
  end

  namespace :admins do
    resources :orders
  end

  namespace :admins do
    resources :genres
  end

  namespace :admins do
    resources :items

  end
  get 'admins/top'

  namespace :device do
    get 'registrations/new'
    get 'registrations/create'
    get 'registrations/destroy'
  end

  namespace :admins do
    get 'sessions/new'
    get 'sessions/create'
    get 'sessions/destroy'
  end
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :order_items
	has_many :cart_items, dependent: :destroy
	belongs_to :genre
	attachment :image
	validates :name, presence: true
	validates :introduction, presence: true
	validates :non_tax_price, presence: true
	validates :genre_id, presence: true
	validates :sales_status, presence: true

	enum sales_status: {
		販売中: 0,
		売り切れ: 1
	}

	# admin側item検索機能
	def self.search(search)
		if search
			Item.where(['name LIKE ?', "%#{search}%"])
		else
			Item.all
		end
	end

end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  before_action :authenticate_admin!

  # kaminari表示数設定
  PER = 10

  def index
    # 検索パラメータの有無で条件分岐
    if params[:search] != nil
      items = Item.search(params[:search])
      flash.now[:notice] = "検索の結果 #{items.count} 件みつかりました"
    else
      items = Item.all
      flash.now[:notice] = "全 #{items.count} 件あります"
    end
    # kaminari用
    @items = items.page(params[:page]).per(PER)
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    #binding.pry
    if @item.save
      flash[:success] = "商品 #{@item.name} を新規登録しました"
      redirect_to admins_item_path(@item)
    else
      flash.now[:danger] = "商品を新規登録できませんでした"
      render action: :new
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      flash[:success] = "商品 #{@item.name} を更新しました"
      redirect_to admins_item_path(@item)
    else
      flash.now[:danger] = "商品を更新できませんでした"
      render action: :edit
    end
  end

  private
      def item_params
          params.require(:item).permit(:name, :introduction, :genre_id, :non_tax_price, :image, :sales_status)
      end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_action :authenticate_customer!, only: [:show]


	# TOPページkaminari表示数設定(aki)
	PER = 8

  	def index

  	# 有効なジャンルを取得する(aki)
  	@genres = Genre.where(is_active: true)
    @genre_count = []
    @genres.each do |genre|
      @genre_count << Item.where(genre_id: genre.id).count
    end


  	# URLでgenre指定がない場合(items_path)、もしくは無効なジャンルを指定された場合はidが若い有効なジャンルをリダイレクトで指定する(aki)
  	@genre = Genre.find_by(id: params[:id])
  	if  params[:id] == nil or @genre == nil or @genre.is_active == false
  		redirect_to items_genre_path(@genres.first)
  	end

  	@items = Item.where(genre_id: params[:id]).page(params[:page]).per(PER)
    @items_count = Item.where(genre_id: params[:id]).count
  end

  def show
  	# 有効なジャンルを取得する(aki)
  	@genres = Genre.where(is_active: true)
    @genre_count = []
    @genres.each do |genre|
      @genre_count << Item.where(genre_id: genre.id).count
    end


  	@item = Item.find(params[:id])
  	@cart_item = CartItem.new(item_id: @item.id)
  end

  def about
  end
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admins/items/edit.html.erb
<div class="row">
    <h1>商品編集画面</h1>
</div>
<div class="row">
<%= form_for @item, url: admins_item_path, html: {method: 'PATCH'} do |f| %>
    <div class="col-md-4">
        <%= attachment_image_tag @item, :image, :fill, 300, 300, fallback: "no_image.jpg", size:'300x300', format: 'jpeg', :style=>"max-width: 300px; height: auto;" %>
        <%= f.attachment_field :image %>
    </div>
    <div class="col-md-8">
        <table class="table table-striped table-bordered table-hover">
            <tr>
                <td><label>商品名</label></td>
                <td><%= f.text_field :name %></td>
            </tr>
            <tr>
                <td><label>商品説明</label></td>
                <td><%= f.text_area :introduction %></td>
            </tr>
            <tr>
                <td><label>ジャンル</label></td>
                <td><%= f.select :genre_id, Genre.all.collect{|g| [g.name, g.id]} %></td>
            </tr>
            <tr>
                <td><label>税抜価格</label></td>
                <td><%= f.text_field :non_tax_price %>円</td>
            </tr>
            <tr>
                <td><label>販売<br>ステータス</label></td>
                <td><%= f.select :sales_status, Item.sales_statuses.keys %></td>
            </tr>
        </table>
    </div>
    <div>
        <%= f.submit "変更を保存", class: "btn btn-primary" %>
    </div>
    <% end %>
</div>

app/views/admins/items/index.html.erb
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <h2>商品一覧画面</h2>
        <div style="text-align: right;">
            <%= link_to new_admins_item_path do %>
            <h2><i class="fas fa-plus-square"></i></h2>
            <% end %>
        </div>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row">
    <div class="col-md-2"></div>
    <div class="col-md-8">
        <table class="table table-striped table-bordered table-hover">
            <thead>
                <tr>
                    <th>商品ID</th>
                    <th>商品名</th>
                    <th>税抜価格</th>
                    <th>ジャンル</th>
                    <th>ステータス</th>
                </tr>
            </thead>
            <tbody>
                <% @items.each do |item| %>
                <tr>
                    <td>
                        <%= item.id %>
                    </td>
                    <td>
                        <%= link_to item.name, admins_item_path(item.id) %>
                    </td>
                    <td>
                        <%= "¥#{item.non_tax_price.to_s(:delimited)}" %>
                    </td>
                    <td>
                        <%= item.genre.name %>
                    </td>
                    <td>
                        <%= item.sales_status %>
                    </td>
                </tr>
                <% end %>
            </tbody>
        </table>
    </div>
    <div class="col-md-2"></div>
</div>
<div class="row">
    <div class="col-md-2"></div>
    <%= paginate @items, class: "paginate" %>
    <div class="col-md-2"></div>
</div>

app/views/admins/items/new.html.erb
<h3>商品 新規登録画面</h3>



<%= form_for([:admins, @item]) do |f| %>

	<%= attachment_image_tag @item, :image, fallback: "no_image.jpg"%>
	<%= f.attachment_field :image %>

	  <div>
		<label>商品名</label>
		<%= f.text_field :name %>
	  </div>

	  <div>
		<label>商品説明</label>
		<%= f.text_area :introduction %>
	  </div>
	  
	  <div>
	  	<label>ジャンル</label>
	  	<%= f.select :genre_id, Genre.all.collect{|g| [g.name, g.id]}, {prompt: '選択してください'}  %>
	  </div>

	  <div>
		<label>税抜価格</label>
		<%= f.text_field :non_tax_price %>円
	  </div>
	  
	  <div>
	  	<label>販売<br>ステータス</label>
	  	<%= f.select :sales_status, Item.sales_statuses.keys, {prompt: '選択してください'} %>
	  </div>

	  <div>
	  	<%= f.submit "新規登録" %>
	  </div>

<% end %>

app/views/admins/items/show.html.erb
<div class="row">
    <h1>商品詳細画面</h1>
</div>
<div class="row">
    <div class="col-md-4">
        <%= attachment_image_tag @item, :image, :fill, 300, 300, format: 'jpeg', fallback: "no_image.jpg", size:'300x300', :style=>"max-width: 300px; height: auto;" %>
    </div>
    <div class="col-md-8">
        <table class="table table-striped table-bordered table-hover">
            <tr>
                <th>商品名</th>
                <td>
                    <%= @item.name %>
                </td>
            </tr>
            <tr>
                <th>商品詳細</th>
                <td>
                    <%= @item.introduction %>
                </td>
            </tr>
            <tr>
                <th>ジャンル</th>
                <td>
                    <%= @item.genre.name %>
                </td>
            </tr>
            <tr>
                <th>税込価格（税抜価格）</th>
                <td>
                    <%= "#{(@item.non_tax_price * 1.1).round.to_s(:delimited)}（#{@item.non_tax_price.round.to_s(:delimited)}）円" %>
                </td>
            </tr>
            <tr>
                <th>販売ステータス</th>
                <td>
                    <%= @item.sales_status %>
                </td>
            </tr>
        </table>
    </div>
</div>
<div class="row">
    <%= link_to "編集する", edit_admins_item_path(@item), class: "btn btn-primary" %>
</div>