config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {:registrations => 'customers/registrations', :sessions => 'customers/sessions'}
  devise_for :admins, controllers: {:sessions => 'admins/sessions'}

  # redirect_toにてsign_outを使用するために必要
  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end

  # Aboutページ用
  get 'items/about'

  # Customerトップでのジャンル指定用
  get 'items/genre/:id' => 'items#index', as: 'items_genre'

  resources :items
  resources :orders
  # CUstomer退会確認画面用
  get 'customers/exit'
  resources :customers

  resources :addresses
  resources :order_items

  get 'cart_items/info'
  post 'cart_items/confirm'
  get 'cart_items/confirm'
  get 'cart_items/thanks'
  resources :cart_items do
    collection do
      delete :empty
    end
  end

  root 'items#index'


  namespace :admins do
    resources :customers
  end

  namespace :admins do
    resources :orders
  end

  namespace :admins do
    resources :genres
  end

  namespace :admins do
    resources :items

  end
  get 'admins/top'

  namespace :device do
    get 'registrations/new'
    get 'registrations/create'
    get 'registrations/destroy'
  end

  namespace :admins do
    get 'sessions/new'
    get 'sessions/create'
    get 'sessions/destroy'
  end
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :customer, optional: true
	belongs_to :item, optional: true

	validates :customer_id, presence: true
	validates :item_id, presence: true
	validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }, length: { maximum: 2 }
end

app/controllers/cart_items_controller.rb
class CartItemsController < ApplicationController
  before_action :authenticate_customer!

  def index
    # @cart_items = CartItem.where(customer_id: current_customer.id)
    @cart_items = current_customer.cart_items
  end

  def update
    @cart_item = CartItem.find(params[:id])
    if @cart_item.update(cart_item_params)
      flash[:success] = "#{@cart_item.item.name} の数量を変更しました"
      redirect_to cart_items_path
    else
      flash.now[:danger] = "#{@cart_item.item.name} の数量を変更できませんでした"
      @cart_items = current_customer.cart_items
      render action: :index
    end
  end

  def create
    if cart_exist?(params[:cart_item][:item_id].to_i)
      cart_item  = current_customer.cart_items.find_by(item_id: params[:cart_item][:item_id].to_i)
      cart_item.amount += params[:cart_item][:amount].to_i
      cart_item.save
      flash[:success] = "カートに #{cart_item.item.name} を #{cart_item.amount} 個追加しました"
      redirect_to cart_items_path
    else
      @cart_item = CartItem.new(cart_item_params)
      if @cart_item.save
        flash[:success] = "カートに #{@cart_item.item.name} を #{@cart_item.amount} 個追加しました"
        redirect_to cart_items_path
      else
        flash.now[:danger] = "カートに #{@cart_item.item.name} を追加できませんでした"
        render item_path (@cart_item.item_id)
      end
    end
  end

  def info
  end

  def confirm
    # binding.pry
    if params[:ship_address] == "registered_address"
      ad = Address.where(customer_id: current_customer.id).find(params[:ship_nummber].to_i)
      @postal_code = ad.postal_code
      @address = ad.address
      @name = ad.name
    elsif params[:ship_address] == "new_address"
      ad = Address.new(
        customer_id: current_customer.id,
        address: params[:address],
        postal_code: params[:postal_code],
        name: params[:name]
        )
      unless ad.save
        flash.now[:danger] = "新しいお届け先を正しく入力してください"
        render action: :info
      end
      flash.now[:success] = "新しいお届け先を登録しました"
      @postal_code = ad.postal_code
      @address = ad.address
      @name = ad.name
    elsif params[:ship_address] == "customer_address"
      ad = current_customer
      @postal_code = ad.postal_code
      @address = ad.address
      @name = "#{ad.name_last} #{ad.name_first}"
    end
    @payment = params[:payment]
    @cart_items = current_customer.cart_items
    @tax = 1.1
  end

  def thanks
    cart_items = current_customer.cart_items
    order = Order.new
    order.customer_id = current_customer.id
    order.order_status = :入金待ち
    order.shipping = 800
    order.ship_name = params[:ship_name]
    order.ship_address = params[:address]
    order.postal_code = params[:postal_code]
    order.payment = params[:payment]
    order.save

    flash.now[:success] = "注文が確定しました"

    cart_items.each do |item|
      order_item = OrderItem.new
      order_item.order_id = order.id
      order_item.item_id = item.item.id
      order_item.amount = item.amount
      order_item.tax_price = (item.item.non_tax_price*1.1).round
      order_item.production_status = :着手不可
      order_item.save

      CartItem.find_by(item_id: item.item_id,customer_id: current_customer.id).destroy
    end

  end

  def destroy
    @cart_item = CartItem.find(params[:id])
    @cart_item.destroy
    flash[:success] = "カートから #{@cart_item.item.name} を削除しました"
    redirect_to cart_items_path
  end

  def empty
    @cart_item = CartItem.where(customer_id: current_customer)
    @cart_item.delete_all
    flash[:success] = "カートを空にしました"
    redirect_to items_path
  end

  private

  def cart_exist?(item_id)
    cart = CartItem.find_by(customer_id: current_customer.id, item_id: item_id)
    cart.present?
  end
  def cart_item_params
    params.require(:cart_item).permit(:amount, :item_id, :customer_id)
  end

end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/views/cart_items/confirm.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-8">
            <h2>注文情報確認</h2>
            <div class="panel panel-primary">
                <div class="panel-heading" style="text-align: center;">
                    <b>商品情報</b>
                </div>
                <table class="table table-bordered table-content">
                    <tbody>
                        <tr class="info">
                            <th>商品名</th>
                            <th>単価(税込)</th>
                            <th>数量</th>
                            <th>小計</th>
                        </tr>
                        <% total = 0 %>
                        <% @cart_items.each do |item| %>
                        <tr>
                            <td>
                                <%= item.item.name %>
                            </td>
                            <td>
                                <%= tax_price = "¥#{((item.item.non_tax_price * @tax).floor).to_s(:delimited)}" %>
                            </td>
                            <td>
                                <%= item.amount %>
                            </td>
                            <td>
                                <%= "¥#{((item.item.non_tax_price * @tax).floor * item.amount).to_s(:delimited)}" %>
                            </td>
                        </tr>
                        <% total = total + (item.item.non_tax_price*item.amount*@tax).round %>
                        <% end %>
                    </tbody>
                </table>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading" style="text-align: center;">
                    <b>請求情報</b>
                </div>
                <table class="table table-bordered table-content">
                    <tbody>
                        <tr>
                            <th class="info">送料</th>
                            <td>¥800</td>
                        </tr>
                        <tr class="inro">
                            <th class="info">商品合計</th>
                            <td>
                                <%= "¥#{total.to_s(:delimited)}" %>
                            </td>
                        </tr>
                        <tr>
                            <th class="info">請求金額</th>
                            <td>
                                <%= "¥#{(800 + total).to_s(:delimited)}" %>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading" style="text-align: center;">
                    <b>支払い方法/お届け先</b>
                </div>
                <table class="table">
                    <tr>
                        <th class="info" style="width: 80px;">支払方法</th>
                        <td>
                            <%= @payment %>
                        </td>
                    </tr>
                    <tr>
                        <th class="info">お届け先</th>
                        <td>
                            <%= "#{@postal_code} #{@address} #{@name}" %>
                        </td>
                    </tr>
                </table>
            </div>
            <%= link_to cart_items_thanks_path(:ship_name => @name, :address => @address, :postal_code => @postal_code, :payment => @payment), class: "btn btn-warning btn-block" do %>
            <b>購入する</b>
            <% end %>
            <div class="col-md-2">
            </div>
        </div>
    </div>
</div>

app/views/cart_items/index.html.erb
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h3>ショッピングカート</h3>
            <div class="panel panel-primary" style="text-align: center;">
                <div class="panel-heading">
                    <b>カート内容</b>
                </div>
                <table class="table table-content table-bordered">
                    <tr class="info">
                        <th>商品名</th>
                        <th>単価(税込)</th>
                        <th style="width: 120px;">個数</th>
                        <th>小計</th>
                        <th>
                            <%= button_to 'カートを空にする', empty_cart_items_path, method: :delete, data: {confirm: 'カートを削除してよろしいですか？'},  class: 'btn-sm btn-danger center-block' %>
                        </th>
                    </tr>
                    <tbody>
                        <% total = 0 %>
                        <% @cart_items.each do |cart_item| %>
                        <tr>
                            <td>
                                <%= attachment_image_tag cart_item.item, :image, :fill,50, 30, format: 'jpeg', fallback: "no_image.jpg", size:'50x30' %>
                                <%= cart_item.item.name %>
                            </td>
                            <td>
                                <%= "¥#{(cart_item.item.non_tax_price* 1.1).round}（税込）"  %>
                            </td>
                            <td>
                                <%= form_for cart_item do |f| %>
                                <div class="input-group" style="">
                                    <%= f.text_field :amount, :size=>"5", class: "form-control"%>
                                    <span class="input-group-btn">
                                        <%= f.submit "変更", class: "btn btn-primary" %>
                                    </span>
                                </div>
                                <% end %>
                            </td>
                            <td>
                                <%= "¥#{(cart_item.item.non_tax_price*cart_item.amount* 1.1).round}（税込）"  %>
                            </td>
                            <td>
                                <%= button_to '削除する', cart_item_path(cart_item), method: :delete, data: {confirm: '商品を削除しますか？'}, class: 'btn-sm btn-danger center-block'%>
                            </td>
                            <% total = total + (cart_item.item.non_tax_price*cart_item.amount*1.1).round %>
                        </tr>
                        <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <%= link_to "買い物を続ける", items_path, class: 'btn-sm btn-primary' %>
        </div>
        <div class="col-md-6" style="text-align: right;">
            <div style="display: inline-block;">
                <table class="table table-content table-bordered">
                    <tr>
                        <th class="info">合計金額</td>
                        <td style="width: 200px; background-color: white;">
                            <b>
                                <%= "¥#{total.to_s(:delimited)}" %></b>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="text-right">
                <% if current_customer.cart_items != [] %>
                <%= link_to "情報入力に進む", cart_items_info_path, class: 'btn btn-block btn-primary' %>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/cart_items/info.html.erb
<div class="container">
    <%= form_tag(cart_items_confirm_path, method: :post)  do %>
    <div class="row">
        <div class="col-md-6">
            <h2>購入情報入力</h2>
            <div class="panel panel-primary">
                <div class="panel-heading" style="text-align: center;">
                    <b>支払い方法</b>
                </div>
                <table class="table">
                    <tr>
                        <label style="padding: 5px 20px;">
                            <%= radio_button_tag :payment, :クレジットカード, {:checked => true}  %>クレジットカード</label><br>
                    </tr>
                    <tr>
                        <label style="padding: 5px 20px;">
                            <%= radio_button_tag :payment, :銀行振込 %>銀行振込</label>
                    </tr>
                </table>
            </div>
        </div>
        <div class="col-md-6"></div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="panel panel-primary">
                <div class="panel-heading" style="text-align: center;">
                    <b>お届け先</b>
                </div>
                <table>
                    <tr>
                        <label style="padding: 5px 20px;">
                            <%= radio_button_tag :ship_address, :customer_address, {:checked => true}  %>ご自身の住所</label><br>
                        <div style="padding: 0 0 20px 40px;">
                            <%= current_customer.postal_code %>
                            <%= current_customer.address %><br>
                            <%= current_customer.name_last %>
                            <%=  current_customer.name_first %><br>
                        </div>
                    </tr>
                    <tr>
                        <label style="padding: 5px 20px;">
                            <%= radio_button_tag :ship_address, :registered_address %>登録済み住所から選択</label><br>
                        <div style="padding: 0 0 20px 40px;">
                            <%= select_tag(:ship_nummber, options_for_select(current_customer.addresses.collect {|a|[a.postal_code + " " + a.address + " " + a.name, a.id]}), include_blank: false) %><br>
                        </div>
                    </tr>
                    <tr>
                        <label style="padding: 5px 20px;">
                            <%= radio_button_tag :ship_address, :new_address %>新しいお届け先</label>
                        <div>
                            <div style="padding: 0 0 20px 40px;">
                                <div>郵便番号(ハイフンなし7桁)<br>
                                    <%= text_field_tag :postal_code, "", {size:"30"} %>
                                </div>
                                <div>住所<br>
                                    <%= text_field_tag :address, "", {size:"70"} %>
                                </div>
                                <div>宛名<br>
                                    <%= text_field_tag :name, "", {size:"30"} %>
                                </div>
                            </div>
                        </div>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <%= submit_tag "確認画面へ", class: "btn btn-primary" %>
    <% end %>
</div>
<!-- ラジオボタンの選択によりフォームの有効無効を切り替え -->
<script>
var checkOption = document.getElementsByName('ship_address');
var postalElem = document.getElementById("postal_code");
var addressElem = document.getElementById("address");
var nameElem = document.getElementById("name");
var registerdElem = document.getElementById("ship_nummber");
var radiobuttonRegisterd = document.getElementById("ship_address_registered_address")

postalElem.disabled = true;
addressElem.disabled = true;
nameElem.disabled = true;
registerdElem.disabled = true;

if(registerdElem.value == ""){
radiobuttonRegisterd.disabled = true;
}

checkOption.forEach(function(e) {
    e.addEventListener("click", function() {
        var shipValue = document.querySelector("input:checked[name=ship_address]").value;

        if (shipValue == "customer_address") {
            postalElem.disabled = true;
            addressElem.disabled = true;
            nameElem.disabled = true;
            registerdElem.disabled = true;
        } else if (shipValue == "registered_address") {
            postalElem.disabled = true;
            addressElem.disabled = true;
            nameElem.disabled = true;
            registerdElem.disabled = false;
        } else if (shipValue == "new_address") {
            postalElem.disabled = false;
            addressElem.disabled = false;
            nameElem.disabled = false;
            registerdElem.disabled = true;
        }
    });
});
</script>

app/views/cart_items/thanks.html.erb
<div class="fluid-box fourth-visual">
    <div class="bg-mask-w">
        <div class="fluid-box-inner">
            <div class="row">
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                    <div class="content-center">
                        <img src="/assets/logo-s.png" style="margin-top: 80px;">
                    </div>
                </div>
                <div class="col-md-4">
                </div>
            </div>
            <div class="row">
                <div class="col-md-2">
                </div>
                <div class="col-md-8">
                    <div class="content-center">
                   <h5 style="font-weight: bold; font-size: 40px;">お買い上げありがとうございました！</h5>
                <br>
                       <p>またのご利用お待ちしてます。</p>
                    </div>
                </div>
                <div class="col-md-2">
                </div>
            </div>
        </div>
    </div>
</div>