config/routes.rb
Rails.application.routes.draw do

  devise_for :customers, controllers: {:registrations => 'customers/registrations', :sessions => 'customers/sessions'}
  devise_for :admins, controllers: {:sessions => 'admins/sessions'}

  # redirect_toにてsign_outを使用するために必要
  devise_scope :customer do
    get '/customers/sign_out' => 'devise/sessions#destroy'
  end

  # Aboutページ用
  get 'items/about'

  # Customerトップでのジャンル指定用
  get 'items/genre/:id' => 'items#index', as: 'items_genre'

  resources :items
  resources :orders
  # CUstomer退会確認画面用
  get 'customers/exit'
  resources :customers

  resources :addresses
  resources :order_items

  get 'cart_items/info'
  post 'cart_items/confirm'
  get 'cart_items/confirm'
  get 'cart_items/thanks'
  resources :cart_items do
    collection do
      delete :empty
    end
  end

  root 'items#index'


  namespace :admins do
    resources :customers
  end

  namespace :admins do
    resources :orders
  end

  namespace :admins do
    resources :genres
  end

  namespace :admins do
    resources :items

  end
  get 'admins/top'

  namespace :device do
    get 'registrations/new'
    get 'registrations/create'
    get 'registrations/destroy'
  end

  namespace :admins do
    get 'sessions/new'
    get 'sessions/create'
    get 'sessions/destroy'
  end
end

app/models/address.rb
class Address < ApplicationRecord
	belongs_to :customer

	validates :customer_id, presence: true
	validates :name, presence: true
	validates :address, presence: true
	validates :postal_code, presence: true, format: {with: /\A[0-9]{7}\z/}
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
	belongs_to :customer, optional: true
	belongs_to :item, optional: true

	validates :customer_id, presence: true
	validates :item_id, presence: true
	validates :amount, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 1 }, length: { maximum: 2 }
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :orders, dependent: :destroy
         has_many :addresses, dependent: :destroy
         has_many :cart_items, dependent: :destroy

         validates :email, presence: true
         validates :name_first, presence: true
         validates :name_last, presence: true
         validates :name_first_kana, presence: true
         validates :name_last_kana, presence: true
         validates :postal_code, presence: true
         validates :address, presence: true
         validates :phone_number, presence: true
         # validates :is_active, presence: true
         # ブーリアン型で判別するときはpresencd:trueが必要ない(yu)


def update_without_current_password(params, *options)
    params.delete(:current_password)

    if params[:password].blank? && params[:password_confirmation].blank?
      params.delete(:password)
      params.delete(:password_confirmation)
    end

    result = update_attributes(params, *options)
    clean_up_passwords
    result
end

# 退会済み会員のログインを受け付けない(aki)
def active_for_authentication?
  super && is_active
end

# admin側customer検索機能
  def self.search(search)
    if search
      # 苗字or名前or各かなor(苗字+名前)で検索
      Customer.where("name_last IN (?) OR name_first IN (?) OR name_last_kana IN (?) OR name_first_kana IN (?) OR (name_last || name_first) IN (?) OR (name_last_kana || name_first_kana) IN (?)" , search, search, search, search, search, search)
    else
      Customer.all
    end
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
	has_many :items

	validates :name, presence: true
	# validates :is_active, presence: true
end

app/models/item.rb
class Item < ApplicationRecord
	has_many :order_items
	has_many :cart_items, dependent: :destroy
	belongs_to :genre
	attachment :image
	validates :name, presence: true
	validates :introduction, presence: true
	validates :non_tax_price, presence: true
	validates :genre_id, presence: true
	validates :sales_status, presence: true

	enum sales_status: {
		販売中: 0,
		売り切れ: 1
	}

	# admin側item検索機能
	def self.search(search)
		if search
			Item.where(['name LIKE ?', "%#{search}%"])
		else
			Item.all
		end
	end

end

app/models/order.rb
class Order < ApplicationRecord
	has_many :order_items, dependent: :destroy
	belongs_to :customer

	validates :customer_id, presence: true
	validates :order_status, presence: true
	validates :shipping, presence: true
	validates :ship_name, presence: true
	validates :ship_address, presence: true
	validates :postal_code, presence: true
	validates :payment, presence: true


   enum payment: {
   	銀行振込: 0,
   	クレジットカード: 1,
   }
  
	enum order_status: {
		入金待ち: 0,
		入金確認: 1,
		製作中: 2,
		発送準備中: 3,
		発送済み: 4
	}

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
	belongs_to :order, dependent: :destroy
	belongs_to :item
	
	enum production_status: {
		着手不可: 0,
		製作待ち: 1,
		製作中: 2,
		製作完了: 3
	}
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_admin!

  def top
	@orders = Order.where(created_at: Time.zone.now.all_day)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  # before_action :authenticate_customer!, only: [:show]


	# TOPページkaminari表示数設定(aki)
	PER = 8

  	def index

  	# 有効なジャンルを取得する(aki)
  	@genres = Genre.where(is_active: true)
    @genre_count = []
    @genres.each do |genre|
      @genre_count << Item.where(genre_id: genre.id).count
    end


  	# URLでgenre指定がない場合(items_path)、もしくは無効なジャンルを指定された場合はidが若い有効なジャンルをリダイレクトで指定する(aki)
  	@genre = Genre.find_by(id: params[:id])
  	if  params[:id] == nil or @genre == nil or @genre.is_active == false
  		redirect_to items_genre_path(@genres.first)
  	end

  	@items = Item.where(genre_id: params[:id]).page(params[:page]).per(PER)
    @items_count = Item.where(genre_id: params[:id]).count
  end

  def show
  	# 有効なジャンルを取得する(aki)
  	@genres = Genre.where(is_active: true)
    @genre_count = []
    @genres.each do |genre|
      @genre_count << Item.where(genre_id: genre.id).count
    end


  	@item = Item.find(params[:id])
  	@cart_item = CartItem.new(item_id: @item.id)
  end

  def about
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_customer!

  def index
  	  @orders = Order.where(customer_id:  current_customer.id)
  	  @order_items = OrderItem.where(order_id: params[:id])
      flash.now[:notice] = "あなたの注文は全 #{@orders.count} 件あります"
  end

  def show
  	  @order = Order.find(params[:id])
  	  @order_item = OrderItem.where(order_id: params[:id])
  end

  def create
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/admins/top.html.erb
<div class="container">
    <div class="row">
    	<h1>管理者画面</h1>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="alert alert-info" style="font-size: 25px;">
                本日の注文件数：<%= link_to @orders.count,  admins_orders_path(key: "today") %>件
            </div>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/46860f55f1.js" crossorigin="anonymous"></script>
</head>

<body>
    <nav class="navbar navbar-default navbar-fixed-top" style="background-color: #ffeaff;">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbarEexample">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse" id="navbarEexample">
                <div class="navbar-right">
                    <ul class="nav navbar-nav" style="color: black;">
                        <!-- Customerがログインしている時 -->
                        <% if current_customer %>
                        <li class="">
                            <%= link_to customer_path(current_customer) do %>
                            <i class="fas fa-user">
                                <%= " #{current_customer.name_last}#{current_customer.name_first}さん" %></i>
                            <% end %>
                        </li>
                        <li class="">
                            <%= link_to items_path, method: :get do %>
                            <i class="fas fa-home"></i>
                            <% end %>
                        </li>
                        <li class="">
                            <%= link_to cart_items_path method: :get do%>
                            <i class="fas fa-shopping-cart"> <span class="badge">
                                    <%= @cart_count_nav %></span></i>
                            <% end %>
                        </li>
                        <li class="">
                            <%= link_to destroy_customer_session_path, method: :delete do %>
                            <i class="fas fa-sign-out-alt"> Logout</i>
                            <% end %>
                        </li>
                        <li class="">
                            <%= link_to items_about_path do %>
                            <i class="fas fa-store">About</i>
                            <% end %>
                        </li>
                        <!-- Adminがログインしている時 -->
                        <% elsif current_admin %>
                        <!-- Item検索機能ここから -->
                        <li style="padding: 10px 10px;">
                            <%= form_tag(admins_items_path,:method => 'get') do %>
                            <div class="input-group" style="width: 150px;">
                                <%= text_field_tag :search, "商品" , {class: "form-control"} %>
                                <span class="input-group-btn">
                                    <%= button_tag :type => "submit", :class =>"btn btn-primary" do %>
                                    <i class="fa fa-search"></i>
                                    <% end %>
                                </span>
                            </div>
                            <% end %>
                            </ll>
                            <!-- Item検索機能ここまで -->
                            <!-- Customer検索機能ここから -->
                        <li style="padding: 10px 10px;">
                            <%= form_tag(admins_customers_path,:method => 'get') do %>
                            <div class="input-group" style="width: 150px;">
                                <%= text_field_tag :search, "顧客", {class: "form-control"} %>
                                <span class="input-group-btn">
                                    <%= button_tag :type => "submit", :class =>"btn btn-primary" do %>
                                    <i class="fa fa-search"></i>
                                    <% end %>
                                </span>
                            </div>
                            <% end %>
                        </li>
                        <!-- Customer検索機能ここまで -->
                        <li class="">
                            <%= link_to admins_top_path do%>
                            <i class="fas fa-user-cog">
                                <%= " #{current_admin.name}さん" %></i>
                            <% end %>
                        </li>
                        <li class="">
                            <%= link_to admins_genres_path do %>
                            <i class="fas fa-object-group"> Genres</i>
                            <% end %>
                        </li>
                        <li class="">
                            <%= link_to admins_customers_path do%>
                            <i class="fas fa-user-friends"> Customers</i>
                            <% end %>
                        </li>
                        <li class="">
                            <%= link_to admins_orders_path do %>
                            <i class="fas fa-sticky-note"> Orders</i>
                            <% end %>
                        </li>
                        <li class="">
                            <%= link_to admins_items_path do %>
                            <i class="fas fa-birthday-cake"> Items</i>
                            <% end %>
                        </li>
                        <li class="">
                            <%= link_to destroy_admin_session_path, method: :delete do %>
                            <i class="fas fa-sign-out-alt"> Logout</i>
                            <% end %>
                        </li>
                        <!-- いずれもログインしていない時 -->
                        <% else %>
                        <li class="">
                            <%= link_to new_customer_session_path do %>
                            <i class="fas fa-sign-in-alt"> Login</i>
                            <% end %>
                        </li>
                        <li class="">
                            <%= link_to new_customer_registration_path do %>
                            <i class="fas fa-user-plus"> Signup</i>
                            <% end %>
                        </li>
                        <li class="">
                            <%= link_to items_about_path do %>
                            <i class="fas fa-store"> About</i>
                            <% end %>
                        </li>
                        <% end %>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <header style="background-size: cover;background-position: 0px 950px ;background-image: url(/assets/background-image1.jpg); position: relative; z-index: 1;">
        <%= link_to image_tag("/assets/logo-s.png",width: '200'), items_path %>
    </header>
    <div class="fluid-box2 fourth-visual">
        <div class="bg-mask-w">
            <div class="wrapper" style="min-height: 100vh;position: relative;padding-bottom: 200px;box-sizing: border-box;" ;>
                <div class="container">
                    <div class="row">
                        <!-- flash表示ここから -->
                        <div class="row　flash text-center flash-deco">
                            <% if flash[:notice] %>
                                <span class="label label-primary">
                                    <i class="fas fa-info-circle"></i>
                                    <%= flash[:notice] %>
                                </span>
                            <% end %>
                            <% if flash[:success] %>
                                <span class="label label-success">
                                    <i class="fas fa-check-circle"></i>
                                    <%= flash[:success] %>
                                </span>
                            <% end %>
                            <% if flash[:danger] %>
                                <span class="label label-danger">
                                    <i class="fas fa-exclamation-circle"></i>
                                    <%= flash[:danger] %>
                                </span>
                            <% end %>
                        </div>
                        <!-- flash表示ここまで -->
                        <%= yield %>
                        </div>
                    </div>
                </div>
                <footer class="page-footer font-lage pt-4" style="position: absolute;bottom: 0;width: 100%;background-size: cover;height: 200px; background-position: 0px 400px ;background-image: url(/assets/background-image1.jpg)">
                    <div class="container">
                        <!-- Social buttons -->
                        <ul class="list-unstyled list-inline text-center" style="margin-top: 10px;">
                            <li class="list-inline-item">
                                <a class="btn-floating btn-fb mx-1">
                                    <i class="fab fa-facebook-f"> </i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a class="btn-floating btn-tw mx-1">
                                    <i class="fab fa-twitter"> </i>
                                </a>
                            </li>
                            <li class="list-inline-item">
                                <a class="btn-floating btn-gplus mx-1">
                                    <i class="fab fa-instagram"> </i>
                                </a>
                            </li>
                        </ul>
                        <div class="row" style="text-align: center;">
                            <p>営業時間 / 11:00～17:00(月～金)<br>
                                休業日 / 土曜日 日曜日 ・祝日<br>
                                住所：〒999-9999　○○県○○市○○町○○　99-99<br>
                                TEL：99-9999-9999<br>
                                MAIL：sample@shop.rakuten.co.jp<br></p>
                        </div>
                        <div class="footer-copyright text-center py-3">© 2020 Copyright:
                            <a href=""> NaganoCake</a>
                        </div>
                    </div>
                </footer>
            </div>
        </div>
    </div>
</body>

</html>